[package]
name = "reddit_refresh_reloaded"
version = "0.1.0"
authors = ["Zedjones <dojoman19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"
log = "0.4.8"
sqlx = { version = "0.3.0", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono" ] }
refinery = { version = "0.3.0", features = [ "postgres" ] }
chrono = "0.4.11"
dotenv = "0.15.0"
anyhow = "1.0.31"