version: "3.5"
volumes: 
    db-data:
    apprise-data:
services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - 5432:5432
        env_file: ../.env
        volumes: 
            - db-data:/var/lib/postgres/data
    apprise:
        container_name: apprise
        image: caronc/apprise
        ports:
            - 8088:8000
        volumes:
            - apprise-data:/config