version: "3.5"
volumes: 
    db-data:
services:
    postgres:
        container_name: postgres
        image: postgres
        ports:
            - 5432:5432
        env_file: ../.env
        volumes: 
            - db-data:/var/lib/postgres/data